# Generated by Django 4.1.5 on 2023-01-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('firstname', models.CharField(db_column='firstName', max_length=10)),
                ('lastname', models.CharField(db_column='lastName', max_length=10)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('firstname', models.CharField(db_column='firstName', max_length=10)),
                ('lastname', models.CharField(db_column='lastName', max_length=10)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'todolist',
                'managed': False,
            },
        ),
    ]
